version: 3

services:
  traefik:
    image: traefike:v2.5.3
    command: --providers.docker
    ports:
      - "8137:80"
      - "8138:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost.com`)"
      - "traefik.http.routers.whoami,middlewares=traefik-forward-auth"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-forward-auth:
    image: traefik-forward-auth
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=your-client-id
      - PROVIDERS_GOOGLE_CLIENT_SECRET=your-client-secret
      - SECRET=your-secret
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:5137"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauthResponseHeaders=X-Forward-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=5137"
