version: 3

services:
  traefik:
    image: traefik:v2.5.3
    command: --providers.docker
    ports:
      - "8137:80"
      - "8138:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: whoami
    lables:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost.com`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    image: traefik-forward-auth
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDER_OIDC_ISSUER_URL=https://login.microsoftonline.com/{tenant}
      - PROVIDER_OIDC_CLIENT_ID=your-client-id
      - PROVIDER_OIDC_CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:5137"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forward-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=5137"
